version: "3.9"
services:
  arena-client:
    volumes:
      - ./config.py:/root/aiarena-client/config.py
      - ./:/root/aiarena-client/host
      # SC2 Maps Path
      # Set this as "- PATH_TO_YOUR_MAPS_FOLDER:/root/StarCraftII/maps"
      - C:\Program Files (x86)\StarCraft II\Maps:/root/StarCraftII/maps  # Standard windows SC2 maps path
#      - ./maps:/root/StarCraftII/maps                                   # Local maps folder
#      - ~/StarCraftII/maps:/root/StarCraftII/maps                       # Relatively standard linux SC2 maps path
    image: aiarena/arenaclient